[package]
name = "m4h-kernel"
description = "The M4H multikernel"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
publish = false

[dependencies]

[lints]
workspace = true
