[package]
name = "m4h-lb"
description = "M4H-LB: TLS-terminating load balancer with Virtual IP failover"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
publish = false

[dependencies]

[lints]
workspace = true
