[package]
name = "m4h-bench"
description = "Benchmarks for M4H components"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
publish = false

[dependencies]

[lints]
workspace = true
