[package]
name = "m4h-bench"
description = "Benchmarks for M4H components"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
publish = false

[dependencies]
crossbeam-queue = "0.3.14"
m4h-platform = { version = "0.0.0", path = "../m4h-platform" }
m4h-ring = { version = "0.0.0", path = "../m4h-ring" }
rtrb = "0.4.0"

[lints]
workspace = true
